export function prBodyPy(config) {
  return `#!/usr/bin/env python3
"""
pipeline/scripts/generate-pr-body.py
Generate a PR description from the evidence package.
Usage: python pipeline/scripts/generate-pr-body.py STORY-001
Generated by @yooti/cli
"""
import json
import sys
import os
from datetime import datetime

def generate(story_id):
    evidence_dir = f".agent/evidence/{story_id}"
    req_path = f".agent/requirements/{story_id}-validated.json"

    story = {}
    if os.path.exists(req_path):
        with open(req_path) as f:
            story = json.load(f)

    title = story.get("title", story_id)
    ac_list = story.get("acceptance_criteria", [])
    ac_rows = ""
    for ac in ac_list:
        ac_rows += f"| {ac['id']}: {ac['then'][:60]} | pending | pending |\\n"

    pr_body = f"""## {story_id}: {title}

### What was changed
<!-- Agent: summarise the implementation here -->

### Why
<!-- Agent: link to business requirement -->

### How to test manually
\\'\\'\\'bash
docker compose up -d
# Test the new feature
\\'\\'\\'

### Acceptance Criteria Status
| Criteria | Status | Test |
|----------|--------|------|
{ac_rows}
### Test Results
- Unit: see .agent/evidence/{story_id}/test-results.json
- Coverage: see .agent/evidence/{story_id}/coverage-summary.json
- Regression: see .agent/evidence/{story_id}/regression-diff.json

### Known Gaps and Deliberate Decisions
<!-- Agent: document uncovered branches or deferred decisions -->

### Security Scan
- Snyk: pending
- Semgrep: pending

### Agent Execution Log
<!-- Agent: iterations, failure types corrected, self-heal count -->

---
Generated by @yooti/cli on {datetime.now().strftime("%Y-%m-%d %H:%M")}
"""

    os.makedirs(evidence_dir, exist_ok=True)
    output_path = f"{evidence_dir}/pr-body.md"
    with open(output_path, "w") as f:
        f.write(pr_body)

    print(f"\\n  PR body written: {output_path}\\n")

if __name__ == "__main__":
    story_id = sys.argv[1] if len(sys.argv) > 1 else "STORY-001"
    generate(story_id)
`;
}
