export function readmeMd(config) {
  const t = '`';
  const tt = '```';
  return `# ${config.projectName}

> Built with [@yooti/cli](https://github.com/yooti/cli) — Autonomous SDLC Pipeline

## Quick start

${tt}bash
# 1. Start the local stack
docker compose up -d

# 2. Add your first story
yooti story:add

# 3. Start the sprint
yooti sprint:start
${tt}

## Stack
${config.stack.includes('node') ? '- **API**: Node.js 20 · TypeScript · Express · PostgreSQL · Redis' : ''}
${config.stack.includes('react') ? '- **Frontend**: React 18 · TypeScript · Vite · shadcn/ui · Playwright · Lighthouse CI' : ''}
${config.stack.includes('python') ? '- **Batch**: Python 3.12 · pandas · boto3 · pytest · moto' : ''}

## How the pipeline works

| Role | Gate | What they decide |
|------|------|-----------------|
| Product Manager | G1 | Stories are ready to build |
| Architect | G2 | Plans are architecturally sound |
| Developer | G3 | PR review and approval |
| QA / SDET | G4 | Quality gates pass |
| Release Manager | G5 | Go / no-go for production |

**Agents handle:** code generation · test writing · regression runs · PR body · deployment.
**Humans own:** all five decisions above. Nothing crosses a gate autonomously.

## Context: ${config.context.toUpperCase()}

${config.context === 'brownfield'
  ? `This is a **brownfield adoption**. Read docs/BROWNFIELD.md before starting.
- Risk surface report: ${t}.agent/discovery/risk-surface.json${t}
- Baseline snapshot: ${t}.agent/snapshots/baseline.json${t}
- Characterization tests required before modifying high-risk files`
  : `This is a **greenfield project**. Read docs/GREENFIELD.md to get started.
- Pattern mandate: ${t}.claude/rules/greenfield-rules.md${t}
- Every file the agent creates sets the standard for future sprints`}

## Project structure

${tt}
.claude/             Agent context — Claude Code reads this automatically
  CLAUDE.md          Master rules: scope, tools, escalation, quality gates
  agents/            6 agent prompts: requirements, codegen, testgen, etc.
  rules/             Scope enforcement + greenfield/brownfield rules
.agent/              Pipeline artifacts — git-tracked
  examples/          Pre-filled requirement + plan files — copy and edit
  requirements/      STORY-NNN-validated.json (generated by story:add)
  plans/             STORY-NNN-T00N.plan.md (generated by story:plan)
  snapshots/         Regression baselines per sprint
  evidence/          Test results, coverage, PR body per story
pipeline/            Framework tooling — stack-agnostic
  schemas/           JSON contracts for all pipeline artifacts
  scripts/           preflight.sh, snapshot.py, regression-diff.py
  infra/             docker-compose.yml, terraform stubs
${config.stack.includes('node') ? 'services/api/         Node.js API service\n' : ''}\
${config.stack.includes('react') ? 'frontend/dashboard/   React frontend\n' : ''}\
${config.stack.includes('python') ? 'batch/analytics/      Python batch jobs\n' : ''}\
docs/                Team playbook — GREENFIELD, BROWNFIELD, GATES
${tt}

## Commands

| Command | What it does |
|---------|-------------|
| ${t}yooti init <name>${t} | Scaffold a new project |
| ${t}yooti story:add${t} | Validate and add a story |
| ${t}yooti sprint:start${t} | Start sprint, capture baseline |
| ${t}yooti preflight${t} | Run pre-flight checks |

## Quality gates (all enforced in CI)

| Check | Threshold | Blocks PR |
|-------|-----------|-----------|
| Lint | 0 warnings | YES |
| Type errors | 0 | YES |
| Unit tests | 100% pass | YES |
| Coverage overall | ≥ 80% | YES |
| Coverage new code | ≥ 90% | YES |
| Regression diff | 0 newly failing | YES |
| Accessibility (axe) | 0 violations | YES |
| Lighthouse perf | ≥ 80 | YES |

---
*Generated by @yooti/cli • ${new Date().toISOString().split('T')[0]}*
`;
}
